[lesion]
distance = 40.0
diameter = 1.0

[target]
distribution = "center"
#coefficients = [1.0, 0.0]
mapto ="circle"
radius = 0.5
#height = 0

[septa]
y = 0.0
x = 0.1

[holes]
width = 0.8  # apothem/inradius
#height = 0.4  # radius/circumradius

[collimator]
length = 12.0
rows = 1
diameter = 75.0

[beamnrc]
rmax = 50.0
blocks = 5
