[[plots]]
name = "Reflection Target Scatter Plot"
phsp = "source"
type = "scatter"
slug = "source_scatter"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Reflection Target Scatter Plot (Whole Field)"
phsp = "source"
type = "scatter"
slug = "source_scatter_contextual"
[plots.extents]
xmax = 50
xmin = -50
ymax = 50
ymin = -50

[[plots]]
name = "Filter Scatter Plot"
phsp = "filter"
type = "scatter"
slug = "filter_scatter"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Collimator Scatter Plot"
phsp = "collimator"
type = "scatter"
slug = "collimator_scatter"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Collimator Scatter Plot (Small Section)"
phsp = "collimator"
type = "scatter"
slug = "collimator_scatter_section"
[plots.extents]
xmax = 1
xmin = -1
ymax = 1
ymin = -1

[[plots]]
type = "energy_fluence"
phsp = "source"
axis = "x"
name = "Reflection Target Energy Fluence along X"
slug = "source_fluence_x"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
type = "energy_fluence"
phsp = "source"
axis = "y"
name = "Reflection Target Energy Fluence along Y"
slug = "source_fluence_y"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
type = "energy_fluence"
phsp = "filter"
axis = "x"
name = "Filter Energy Fluence along X"
slug = "filter_fluence_x"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
type = "energy_fluence"
phsp = "filter"
axis = "y"
name = "Filter Energy Fluence along Y"
slug = "filter_fluence_y"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
type = "energy_fluence"
phsp = "collimator"
axis = "x"
name = "Collimator Energy Fluence along X"
slug = "collimator_fluence_x"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
type = "energy_fluence"
phsp = "collimator"
axis = "y"
name = "Collimator Energy Fluence along Y"
slug = "collimator_fluence_y"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2


[[plots]]
type = "energy_fluence"
phsp = "collimator"
axis = "y"
name = "Collimator Energy Fluence along Y (Small Section)"
slug = "collimator_fluence_y_small"
[plots.extents]
xmax = 1
xmin = -1
ymax = 1
ymin = -1

[[plots]]
name = "Reflection Target Angular Distribution"
phsp = "source"
type = "angular"
slug = "source_angular"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Filter Angular Distribution"
phsp = "filter"
type = "angular"
slug = "filter_angular"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Collimator Angular Distribution"
phsp = "collimator"
type = "angular"
slug = "collimator_angular"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Reflection Target Spectral Distribution"
phsp = "source"
type = "spectral"
slug = "source_spectral"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Filter Spectral Distribution"
phsp = "filter"
type = "spectral"
slug = "filter_spectral"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2

[[plots]]
name = "Collimator Spectral Distribution"
phsp = "collimator"
type = "spectral"
slug = "collimator_spectral"
[plots.extents]
xmax = 40
xmin = -40
ymax = 2
ymin = -2
