
[[shots]]

name = "perspective"
description = "Perspective showing the shape of the collimator"
distance = 81
translation = [4.4, 3.16, 1.43]
rotation = [55, 0, 25]
size = [1600, 700]


[[shots]]

name = "from_anode"
description = "Perspective from the anode"
distance = 27
translation = [0.0, -4.25, 1.1]
rotation = [160, 0, 0]
size = [1600, 700]


[[shots]]

name = "from_lesion"
description = "Perspective from the lesion"
distance = 19
translation = [0.0, -3.0, 0.5]
rotation = [336, 0, 0]
size = [1600, 700]

