# magdalena's
# .2mm to .5mm septa
# 1 row vs 5 rows
# converging vs diverging


# magdalena's

[[simulations]]
name = "Magdalena - 2mm Beam"
summary = "Magdalena's collimator with a 2mm electron beam."
beam-height = 0.2
[simulations.collimator]
path = "collimators/magdalena-collimator-1.egsinp"

[[simulations]]
name = "Magdalena - 10mm Beam"
summary = "Magdalena's collimator with a 10mm electron beam."
beam-height = 1.0
[simulations.collimator]
path = "collimators/magdalena-collimator-1.egsinp"


# septas

[[simulations]]
name = "Converging - 0.2mm Septa"
summary = "Converging collimator with 0.2mm septa."
beam-height = 0.2
[simulations.collimator]
septa = 0.02
hole-width = 0.2
target-shape = "point"

[[simulations]]
name = "Converging - 0.3mm Septa"
summary = "Converging collimator with 0.3mm septa."
beam-height = 0.2
[simulations.collimator]
septa = 0.03
hole-width = 0.2
target-shape = "point"

[[simulations]]
name = "Converging - 0.4mm Septa"
summary = "Converging collimator with 0.4mm septa."
beam-height = 0.2
[simulations.collimator]
septa = 0.04
hole-width = 0.2
target-shape = "point"

[[simulations]]
name = "Converging - 0.5mm Septa"
summary = "Converging collimator with 0.5mm septa."
beam-height = 0.2
[simulations.collimator]
septa = 0.05
hole-width = 0.2
target-shape = "point"

# multiple row

[[simulations]]
name = "Converging - 5 row - 0.5mm Septa"
summary = "Converging collimator, using five rows, 10mm beam, and a 0.5mm septa."
beam-height = 1.0
[simulations.collimator]
septa = 0.05
rows = 5
hole-height = 0.2
target-shape = "point"


# diverging

[[simulations]]
name = "Diverging - 1cm Lesion"
summary = "Diverging collimator. Single row, 2mm hole width, and a 0.2mm septa."
beam-height = 1.0
[simulations.collimator]
septa = 0.02
hole-height = 1.0
target-shape = "circle"

[[simulations]]
name = "Diverging - 2cm Lesion"
summary = "Diverging collimator. Single row, 4mm hole width, and a 0.2mm septa."
beam-height = 1.0
[simulations.collimator]
septa = 0.02
hole-height = 1.0
target-shape = "circle"

[[simulations]]
name = "Diverging - 4cm Lesion"
summary = "Diverging collimator. Single row, 8mm hole width, and a 0.2mm septa."
beam-height = 1.0
[simulations.collimator]
septa = 0.02
hole-height = 1.0
target-shape = "circle"

# test!
[[simulations]]
name = "Test"
summary = "Test (converging collimator with 0.2mm septa)."
beam-height = 0.2
[simulations.collimator]
septa = 0.02
hole-width = 0.2
target-shape = "point"
