# 1 row 2mm beam 2mm holes with varying septas


[[simulations]]
name = "Converging - 0mm Septa"
summary = "Converging collimator with no septa."
beam-height = 0.2
[simulations.collimator]
septa-x = 0.0
septa-y = 0.0
hole-width = 0.2
target-shape = "point"


[[simulations]]
name = "Converging - 50 micron Septa"
summary = "Converging collimator with 50 micron septa."
beam-height = 0.2
[simulations.collimator]
septa-x = 0.005
septa-y = 0.005
hole-width = 0.2
target-shape = "point"

[[simulations]]
name = "Converging - 100 micron Septa"
summary = "Converging collimator with 50 micron septa."
beam-height = 0.2
[simulations.collimator]
septa-x = 0.01
septa-y = 0.01
hole-width = 0.2
target-shape = "point"


[[simulations]]
name = "Converging - 0.5mm Septa"
summary = "Converging collimator with 0.5mm septa."
beam-height = 0.2
[simulations.collimator]
septa-x = 0.05
septa-y = 0.05
hole-width = 0.2
target-shape = "point"


# larger hole
[[simulations]]
name = "Converging - 3mm hole"
summary = "Converging collimator with 4mm wide holes."
beam-height = 0.2
[simulations.collimator]
septa-x = 0.05
septa-y = 0.05
hole-width = 0.4
target-shape = "point"

# multiple row
[[simulations]]
name = "Converging - 5 row"
summary = "Converging collimator, using five rows, 10mm beam, and a 0.5mm septa."
beam-height = 1.0
[simulations.collimator]
rows = 5
septa-x = 0.05
septa-y = 0.05
hole-width = 0.2
target-shape = "point"


# diverging (lesions)
[[simulations]]
name = "Diverging - 1cm Lesion"
summary = "Diverging collimator. Single row, 2mm hole width, and no minimum septa."
beam-height = 1.0
lesion-diameter = 1.0
[simulations.collimator]
septa-x = 0.0
septa-y = 0.0
hole-width = 0.2
target-shape = "circle"

[[simulations]]
name = "Diverging - 2cm Lesion"
summary = "Diverging collimator. Single row, 4mm hole width, and no minimum septa."
beam-height = 1.0
lesion-diameter = 2.0
[simulations.collimator]
septa-x = 0.0
septa-y = 0.0
hole-width = 0.4
target-shape = "circle"

[[simulations]]
name = "Diverging - 4cm Lesion"
summary = "Diverging collimator. Single row, 8mm hole width, and no minimum septa."
beam-height = 1.0
lesion-diameter = 4.0
[simulations.collimator]
septa-x = 0.0
septa-y = 0.0
hole-width = 0.8
target-shape = "circle"

# divering (5 rows)
[[simulations]]
name = "Diverging - 5 rows"
summary = "Diverging collimator. Five rows, 2mm hole width, and no minimum septa."
beam-height = 1.0
[simulations.collimator]
septa-x = 0.0
septa-y = 0.0
hole-width = 0.2
target-shape = "circle"
