grace = "grace.toml"
screenshots = "screenshots.toml"

pegs4 = "allkV"

# maximum extent of all component modules
rmax = 50.0

# reflect instead of simulating both sides

reflect = true

desired-histories = 1e10

# y in cm
beam-width = 1.0
# z in cm
# beam-height = 0.5
# gap between incident electron beams
beam-gap = 0.0

# electron beam source to target in cm
target-distance = 50.0
# length of reflection target
target-length = 75.0
target-angle = 45.0

lesion-diameter = 1.0

dose-recycle = 99
dose-photon-splitting = 20
phantom-isocenter = [0, 10, 0]
phantom = "phantoms/20cm-2mm-cylinder.egsphant"

beamnrc-template = "templates/template.egsinp"
stationary-dose-template = "templates/dose_template.egsinp"
arc-dose-template = "templates/arc_dose_template.egsinp"

